package view;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import modal.bean.Usuario;
import modal.dao.UsuarioDao;

public class TelaUpUsuario extends javax.swing.JInternalFrame {

    public static TelaUpUsuario instancia = null;
    private final ImageIcon icone = new ImageIcon("images//logo-bmm.png");

    public TelaUpUsuario() {
        initComponents();
        instancia = this;

        trataFechamento();
    }

    private void trataFechamento() {
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                instancia = null;
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }

    public void setValoresUsuario(String id, String nome, String login, String senha, String cod) {
        lbUpUValor.setText(id);
        txtUpNomeU.setText(nome);
        txtUpLoginU.setText(login);
        txtUpSenhaU.setText(senha);
        txtUpCodU.setText(cod);
    }

    public void centralizaTela() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInfUsuario = new javax.swing.JPanel();
        lbUpU = new javax.swing.JLabel();
        lbUpUValor = new javax.swing.JLabel();
        lbUpNomeU = new javax.swing.JLabel();
        lbUpLoginU = new javax.swing.JLabel();
        lbUpSenhaU = new javax.swing.JLabel();
        lbUpCodU = new javax.swing.JLabel();
        txtUpNomeU = new javax.swing.JTextField();
        txtUpLoginU = new javax.swing.JTextField();
        txtUpSenhaU = new javax.swing.JPasswordField();
        txtUpCodU = new javax.swing.JTextField();
        btnUpConfirma = new javax.swing.JButton();
        btnUpCancela = new javax.swing.JButton();

        setClosable(true);
        setTitle("Atualizar Usuário");

        pInfUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lbUpU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpU.setText("Usuário:");

        lbUpUValor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpUValor.setText("0");

        lbUpNomeU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpNomeU.setText("Nome:");

        lbUpLoginU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpLoginU.setText("Login:");

        lbUpSenhaU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpSenhaU.setText("Senha:");

        lbUpCodU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbUpCodU.setText("Código de Usuário:");

        javax.swing.GroupLayout pInfUsuarioLayout = new javax.swing.GroupLayout(pInfUsuario);
        pInfUsuario.setLayout(pInfUsuarioLayout);
        pInfUsuarioLayout.setHorizontalGroup(
            pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfUsuarioLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfUsuarioLayout.createSequentialGroup()
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbUpCodU)
                            .addComponent(lbUpSenhaU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpCodU, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpSenhaU, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInfUsuarioLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbUpLoginU)
                            .addComponent(lbUpNomeU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpLoginU, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpNomeU, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(pInfUsuarioLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lbUpU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUpUValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pInfUsuarioLayout.setVerticalGroup(
            pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfUsuarioLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUpU)
                    .addComponent(lbUpUValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUpNomeU)
                    .addComponent(txtUpNomeU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUpLoginU)
                    .addComponent(txtUpLoginU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUpSenhaU)
                    .addComponent(txtUpSenhaU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUpCodU)
                    .addComponent(txtUpCodU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnUpConfirma.setText("Confirmar");
        btnUpConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaAtualizacao(evt);
            }
        });

        btnUpCancela.setText("Cancelar");
        btnUpCancela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaAtualizacao(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnUpConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnUpCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pInfUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pInfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaAtualizacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaAtualizacao
        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo atualizar os dados?", "Atualização", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icone) == JOptionPane.YES_OPTION) {

            Usuario u = new Usuario();
            UsuarioDao daoU = new UsuarioDao();

            u.setId(Integer.parseInt(lbUpUValor.getText()));
            u.setNome(txtUpNomeU.getText());
            u.setLogin(txtUpLoginU.getText());
            u.setSenha(String.valueOf(txtUpSenhaU.getPassword()));
            u.setCodT(txtUpCodU.getText());
            daoU.update(u);

            try {
                setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaUpUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmaAtualizacao

    private void cancelaAtualizacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaAtualizacao
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaUpUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelaAtualizacao


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpCancela;
    private javax.swing.JButton btnUpConfirma;
    private javax.swing.JLabel lbUpCodU;
    private javax.swing.JLabel lbUpLoginU;
    private javax.swing.JLabel lbUpNomeU;
    private javax.swing.JLabel lbUpSenhaU;
    private javax.swing.JLabel lbUpU;
    private javax.swing.JLabel lbUpUValor;
    private javax.swing.JPanel pInfUsuario;
    private javax.swing.JTextField txtUpCodU;
    private javax.swing.JTextField txtUpLoginU;
    private javax.swing.JTextField txtUpNomeU;
    private javax.swing.JPasswordField txtUpSenhaU;
    // End of variables declaration//GEN-END:variables
}
