package view;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import modal.dao.UsuarioDao;

public class TelaInicial extends javax.swing.JFrame {

    public String login = "";
    private final ImageIcon icone = new ImageIcon("images//logo-bmm.png");

    public TelaInicial() {
        initComponents();
        setIconImage(icone.getImage());
        acesso();

        txtLogin.requestFocus();

    }

    private void desabilitaMenu(JMenu menu, String op) {
        menu.setEnabled(false);
        menu.setForeground(new Color(153, 153, 153));

        if (op.equals("on")) {
            menu.setEnabled(true);
        }
        menu.setForeground(Color.BLACK);
    }

    private void desabilitaMenuItem(JMenuItem menuItem, String op) {
        menuItem.setEnabled(false);
        menuItem.setForeground(new Color(153, 153, 153));

        if (op.equals("on")) {
            menuItem.setEnabled(true);
        }
        menuItem.setForeground(Color.BLACK);
    }

    private void acesso() {

        if (login.equals("")) {

            desabilitaMenu(menuCadastrar, "off");
            desabilitaMenu(menuConsultar, "off");
            desabilitaMenuItem(menuUsuarios, "off");
            desabilitaMenuItem(menuTrocarUsuarios, "off");
            telaLogin.setVisible(true);
        }

        if (login.equals("admin")) {
            desabilitaMenu(menuInicio, "on");
            desabilitaMenu(menuCadastrar, "on");
            desabilitaMenu(menuConsultar, "on");
            desabilitaMenuItem(menuUsuarios, "on");
            desabilitaMenuItem(menuTrocarUsuarios, "on");
        }

        if (login.equals("comum")) {
            desabilitaMenu(menuInicio, "on");
            desabilitaMenu(menuCadastrar, "off");
            desabilitaMenu(menuConsultar, "on");
            desabilitaMenuItem(menuTrocarUsuarios, "on");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        telaLogin = new javax.swing.JPanel();
        boxLogin = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        txtSenha = new config.JPassWordFieldHint(new JPasswordField(), "images/padlock.png", "Senha");
        ;
        txtLogin = new config.JTextFieldHint(new JTextField(), "images/user-icon.png", "Nome de Usuário");
        ;
        lbLogin2 = new javax.swing.JLabel();
        btnLoginEntrar = new javax.swing.JButton();
        txtLoginCadastro = new javax.swing.JLabel();
        lbLogin3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuTrocarUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuDesmatamento = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bmm Nature");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        telaLogin.setBackground(new java.awt.Color(249, 234, 229));
        telaLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        telaLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        boxLogin.setBackground(new java.awt.Color(255, 153, 102));

        lbLogin.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("Login");

        javax.swing.GroupLayout boxLoginLayout = new javax.swing.GroupLayout(boxLogin);
        boxLogin.setLayout(boxLoginLayout);
        boxLoginLayout.setHorizontalGroup(
            boxLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        boxLoginLayout.setVerticalGroup(
            boxLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLoginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtSenha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtLogin.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        lbLogin2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin2.setText("Entre com suas credenciais");
        lbLogin2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLoginEntrar.setBackground(new java.awt.Color(77, 77, 77));
        btnLoginEntrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoginEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginEntrar.setText("Entrar");
        btnLoginEntrar.setBorderPainted(false);
        btnLoginEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginEntrar.setFocusPainted(false);
        btnLoginEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginEntrarPassaMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginEntrarTiraMouse(evt);
            }
        });
        btnLoginEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEntrar(evt);
            }
        });

        txtLoginCadastro.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtLoginCadastro.setText("Cadastre-se");
        txtLoginCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLoginCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chamaTelaCadUsuarioInicio(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLoginCadastroPssaMouse(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLoginCadastroTiraMouse(evt);
            }
        });

        lbLogin3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lbLogin3.setText("Ainda não tem conta?");

        javax.swing.GroupLayout telaLoginLayout = new javax.swing.GroupLayout(telaLogin);
        telaLogin.setLayout(telaLoginLayout);
        telaLoginLayout.setHorizontalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, telaLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnLoginEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(boxLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lbLogin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginCadastro)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLoginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin)
                    .addComponent(txtSenha))
                .addGap(50, 50, 50))
        );
        telaLoginLayout.setVerticalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addComponent(boxLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbLogin2)
                .addGap(11, 11, 11)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginCadastro)
                    .addComponent(lbLogin3))
                .addGap(18, 18, 18)
                .addComponent(btnLoginEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        desktop.add(telaLogin);
        telaLogin.setBounds(647, 99, 470, 331);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        desktop.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 700);

        menuInicio.setText("Início");
        menuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuUsuarios.setText("Usuários");
        menuUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaTelaCadUsuario(evt);
            }
        });
        menuInicio.add(menuUsuarios);

        menuTrocarUsuarios.setText("Trocar de Usuário");
        menuTrocarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTrocarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocaUsuario(evt);
            }
        });
        menuInicio.add(menuTrocarUsuarios);
        menuInicio.add(jSeparator1);

        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair(evt);
            }
        });
        menuInicio.add(menuSair);

        barraMenu.add(menuInicio);

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuDesmatamento.setText("Desmatamento");
        menuDesmatamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDesmatamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaTelaCadDesmatamento(evt);
            }
        });
        menuCadastrar.add(menuDesmatamento);

        barraMenu.add(menuCadastrar);

        menuConsultar.setText("Consultar");
        menuConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chamaTelaConsulta(evt);
            }
        });
        barraMenu.add(menuConsultar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginEntrarPassaMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginEntrarPassaMouse
        btnLoginEntrar.setBackground(new Color(255, 153, 102));
        btnLoginEntrar.setForeground(new Color(77, 77, 77));
    }//GEN-LAST:event_btnLoginEntrarPassaMouse

    private void btnLoginEntrarTiraMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginEntrarTiraMouse
        btnLoginEntrar.setBackground(new Color(77, 77, 77));
        btnLoginEntrar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLoginEntrarTiraMouse

    private void txtLoginCadastroPssaMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginCadastroPssaMouse
        txtLoginCadastro.setForeground(new Color(255, 153, 102));
    }//GEN-LAST:event_txtLoginCadastroPssaMouse

    private void txtLoginCadastroTiraMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginCadastroTiraMouse
        txtLoginCadastro.setForeground(new Color(77, 77, 77));
    }//GEN-LAST:event_txtLoginCadastroTiraMouse

    private void loginEntrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEntrar

        UsuarioDao dao = new UsuarioDao();

        if (dao.verificaLogin(txtLogin.getText(), txtSenha.getText())) {
            JOptionPane.showMessageDialog(null, "Acesso Confirmado!", "Acesso", JOptionPane.INFORMATION_MESSAGE, icone);
            telaLogin.setVisible(false);

            login = dao.verificaUsuario(txtLogin.getText(), txtSenha.getText());
            acesso();

        } else {
            JOptionPane.showMessageDialog(null, "Acesso Negado!", "Acesso", JOptionPane.INFORMATION_MESSAGE, icone);
        }


    }//GEN-LAST:event_loginEntrar

    private void trocaUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocaUsuario
        JInternalFrame[] frames = desktop.getAllFrames();
        for (int i = 0; i < frames.length; i++) {
            try {
                frames[i].setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        login = "";
        txtSenha.setText("");
        acesso();

    }//GEN-LAST:event_trocaUsuario

    private void chamaTelaCadUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaTelaCadUsuario
        if (TelaCadUsuario.instancia == null) {
            TelaCadUsuario cadUsuario = new TelaCadUsuario();
            desktop.add(cadUsuario);
            cadUsuario.setVisible(true);
            cadUsuario.centralizaTela();
        } else {
            TelaCadUsuario.instancia.toFront();
        }
    }//GEN-LAST:event_chamaTelaCadUsuario

    private void chamaTelaCadDesmatamento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaTelaCadDesmatamento
        if (TelaCadDesmatamento.instancia == null) {
            TelaCadDesmatamento cadDemastamento = new TelaCadDesmatamento(txtLogin.getText());
            desktop.add(cadDemastamento);
            cadDemastamento.setVisible(true);
            cadDemastamento.centralizaTela();
        } else {
            TelaCadDesmatamento.instancia.toFront();
        }
    }//GEN-LAST:event_chamaTelaCadDesmatamento

    private void Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair
        System.exit(0);
    }//GEN-LAST:event_Sair

    private void chamaTelaCadUsuarioInicio(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chamaTelaCadUsuarioInicio
        if (TelaCadUsuarioInicio.instancia == null) {
            TelaCadUsuarioInicio cadUsuarioInicio = new TelaCadUsuarioInicio();
            desktop.add(cadUsuarioInicio);
            cadUsuarioInicio.setVisible(true);
            cadUsuarioInicio.centralizaTela();
        } else {
            TelaCadUsuarioInicio.instancia.toFront();
        }
    }//GEN-LAST:event_chamaTelaCadUsuarioInicio

    private void chamaTelaConsulta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chamaTelaConsulta
        if (!login.equals("")) {
            if (TelaConsulta.instancia == null) {
                TelaConsulta consulta = new TelaConsulta();
                desktop.add(consulta);
                consulta.setVisible(true);
                consulta.centralizaTela();
            } else {
                TelaConsulta.instancia.toFront();
            }
        }
    }//GEN-LAST:event_chamaTelaConsulta

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JPanel boxLogin;
    private javax.swing.JButton btnLoginEntrar;
    public javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogin2;
    private javax.swing.JLabel lbLogin3;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenuItem menuDesmatamento;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuTrocarUsuarios;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JPanel telaLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JLabel txtLoginCadastro;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
