package view;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import modal.bean.Desmatamento;
import modal.dao.BDBMM;
import modal.dao.DesmatamentoDao;
import modal.dao.UsuarioDao;

public class TelaUpDesmatamento extends javax.swing.JInternalFrame {

    public static TelaUpDesmatamento instancia = null;
    private final String usuario;
    private final ImageIcon icone = new ImageIcon("images//logo-bmm.png");

    public TelaUpDesmatamento(String usuario) {
        initComponents();
        instancia = this;
        this.usuario = usuario;

        trataFechamento();
    }

    private void trataFechamento() {
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                instancia = null;
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }

    public void setValoresDesmatamento(String id, String bioma, String ano, String estado, String areaDesmatada) {

        BDBMM bd = new BDBMM();

        lbDesValor.setText(id);
        txtAreaDesmatada.setText(areaDesmatada);
        bd.addItem("SELECT sigla_estado, nome_estado FROM estado", "nome_estado", "sigla_estado", cboEstado);
        bd.addItem("SELECT DISTINCT nome_bioma FROM bioma", "nome_bioma", cboBioma);
        bd.addItem("SELECT ano FROM ano", "ano", cboAno);

        cboAno.getModel().setSelectedItem(ano);
        cboBioma.getModel().setSelectedItem(bioma);

        for (int i = 0; i < cboEstado.getItemCount(); i++) {
            String siglaEstado = cboEstado.getModel().getElementAt(i);
            if (siglaEstado.substring(siglaEstado.length() - 2).equals(estado)) {
                cboEstado.getModel().setSelectedItem(siglaEstado);
                break;
            }
        }
    }

    public void centralizaTela() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpConfirma = new javax.swing.JButton();
        btnUpCancela = new javax.swing.JButton();
        pInfOcorrido = new javax.swing.JPanel();
        lbBioma = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        lbAreaDesmatada = new javax.swing.JLabel();
        txtAreaDesmatada = new javax.swing.JTextField();
        cboBioma = new javax.swing.JComboBox<>();
        cboAno = new javax.swing.JComboBox<>();
        cboEstado = new javax.swing.JComboBox<>();
        lbDes = new javax.swing.JLabel();
        lbDesValor = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Atualizar Desmatamento");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(853, 263));
        setPreferredSize(new java.awt.Dimension(853, 263));

        btnUpConfirma.setText("Confirmar");
        btnUpConfirma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaAtualizacao(evt);
            }
        });

        btnUpCancela.setText("Cancelar");
        btnUpCancela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaAtualizacao(evt);
            }
        });

        pInfOcorrido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Ocorrido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lbBioma.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbBioma.setText("Bioma:");

        lbEstado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbEstado.setText("Estado:");

        lbAno.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbAno.setText("Ano:");

        lbAreaDesmatada.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbAreaDesmatada.setText("Área Desmatada (km²):");

        lbDes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbDes.setText("Desmatamento:");

        lbDesValor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbDesValor.setText("0");

        javax.swing.GroupLayout pInfOcorridoLayout = new javax.swing.GroupLayout(pInfOcorrido);
        pInfOcorrido.setLayout(pInfOcorridoLayout);
        pInfOcorridoLayout.setHorizontalGroup(
            pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfOcorridoLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(lbDes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDesValor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pInfOcorridoLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfOcorridoLayout.createSequentialGroup()
                        .addComponent(lbBioma)
                        .addGap(10, 10, 10)
                        .addComponent(cboBioma, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(lbAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfOcorridoLayout.createSequentialGroup()
                        .addComponent(lbEstado)
                        .addGap(10, 10, 10)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbAreaDesmatada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAreaDesmatada, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pInfOcorridoLayout.setVerticalGroup(
            pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfOcorridoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDes)
                    .addComponent(lbDesValor))
                .addGap(18, 18, 18)
                .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbBioma)
                        .addComponent(cboBioma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbAno)
                        .addComponent(cboAno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEstado))
                    .addGroup(pInfOcorridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbAreaDesmatada)
                        .addComponent(txtAreaDesmatada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnUpConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInfOcorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pInfOcorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaAtualizacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaAtualizacao

        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo atualizar os dados?", "Atualização", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icone) == JOptionPane.YES_OPTION) {
            String siglaEstado;
            siglaEstado = cboEstado.getSelectedItem().toString();

            Desmatamento des = new Desmatamento();
            DesmatamentoDao desDao = new DesmatamentoDao();
            UsuarioDao uDao = new UsuarioDao();
            
            if (desDao.verificaEstadoBioma(cboBioma.getSelectedItem().toString(), siglaEstado.substring(siglaEstado.length() - 2))) {

                des.setId(Integer.parseInt(lbDesValor.getText()));
                des.setBioma(cboBioma.getSelectedItem().toString());
                des.setAno(Integer.parseInt(cboAno.getSelectedItem().toString()));
                des.setEstado(siglaEstado.substring(siglaEstado.length() - 2));
                des.setAreaDesmatada(Integer.parseInt(txtAreaDesmatada.getText()));
                des.setUsuario(uDao.verificaUsuario(usuario));
                desDao.update(des);

                try {
                    setClosed(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(TelaUpDesmatamento.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este estado não tem o bioma especificado!", "Atenção", JOptionPane.INFORMATION_MESSAGE, icone);
            }
        }
    }//GEN-LAST:event_confirmaAtualizacao

    private void cancelaAtualizacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaAtualizacao
        try {
            setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaUpDesmatamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelaAtualizacao


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpCancela;
    private javax.swing.JButton btnUpConfirma;
    private javax.swing.JComboBox<String> cboAno;
    private javax.swing.JComboBox<String> cboBioma;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAreaDesmatada;
    private javax.swing.JLabel lbBioma;
    private javax.swing.JLabel lbDes;
    private javax.swing.JLabel lbDesValor;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JPanel pInfOcorrido;
    private javax.swing.JTextField txtAreaDesmatada;
    // End of variables declaration//GEN-END:variables
}
