package view;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modal.bean.Usuario;
import modal.dao.UsuarioDao;

public final class TelaCadUsuario extends javax.swing.JInternalFrame {

    public static TelaCadUsuario instancia = null;
    private final ImageIcon icone = new ImageIcon("images//logo-bmm.png");

    public TelaCadUsuario() {
        initComponents();
        instancia = this;
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        tbUsuario.setRowSorter(new TableRowSorter(modelo));
        leTabelaUsuario();

        trataFechamento();
    }

    private void trataFechamento() {
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }

            @Override
            public void internalFrameOpened(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                instancia = null;
            }

            @Override
            public void internalFrameIconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeiconified(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
            }

            @Override
            public void internalFrameDeactivated(InternalFrameEvent e) {
            }
        });
    }

    public void centralizaTela() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void leTabelaUsuario() {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);

        UsuarioDao uDao = new UsuarioDao();

        for (Usuario user : uDao.read()) {

            modelo.addRow(new Object[]{
                user.getId(),
                user.getNome(),
                user.getLogin(),
                user.getSenha(),
                user.getCodT(),
                user.getNomeT(),
                user.getUltimaModificacao()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pInfUsuario = new javax.swing.JPanel();
        lbCadNomeU = new javax.swing.JLabel();
        lbCadLoginU = new javax.swing.JLabel();
        lbCadSenhaU = new javax.swing.JLabel();
        lbCadCodU = new javax.swing.JLabel();
        txtCadNomeU = new javax.swing.JTextField();
        txtCadLoginU = new javax.swing.JTextField();
        txtCadSenhaU = new javax.swing.JPasswordField();
        txtCadCodU = new javax.swing.JTextField();
        lbInfCod = new javax.swing.JLabel();
        pListaUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        btnCadUsuario = new javax.swing.JButton();
        btnUpUsuario = new javax.swing.JButton();
        btnDelUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 234, 229));
        setClosable(true);
        setTitle("Cadastrar Usuário");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        pInfUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        lbCadNomeU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCadNomeU.setText("Nome:");

        lbCadLoginU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCadLoginU.setText("Login:");

        lbCadSenhaU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCadSenhaU.setText("Senha:");

        lbCadCodU.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbCadCodU.setText("Código de Usuário:");

        lbInfCod.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbInfCod.setText("Caso não tenha o código de usuário, coloque \"bmm-comum2019\".");

        javax.swing.GroupLayout pInfUsuarioLayout = new javax.swing.GroupLayout(pInfUsuario);
        pInfUsuario.setLayout(pInfUsuarioLayout);
        pInfUsuarioLayout.setHorizontalGroup(
            pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfUsuarioLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInfUsuarioLayout.createSequentialGroup()
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCadCodU)
                            .addComponent(lbCadSenhaU)
                            .addComponent(lbCadLoginU)
                            .addComponent(lbCadNomeU))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadLoginU, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadCodU, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadNomeU, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadSenhaU, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbInfCod))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pInfUsuarioLayout.setVerticalGroup(
            pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadNomeU)
                    .addComponent(txtCadNomeU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadLoginU)
                    .addComponent(txtCadLoginU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadSenhaU)
                    .addComponent(txtCadSenhaU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pInfUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadCodU)
                    .addComponent(txtCadCodU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lbInfCod)
                .addGap(30, 30, 30))
        );

        pListaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N

        tbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Login", "Senha", "Código de Usuário", "Tipo de Usuário", "Última Modificação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbUsuario);
        if (tbUsuario.getColumnModel().getColumnCount() > 0) {
            tbUsuario.getColumnModel().getColumn(0).setMinWidth(25);
            tbUsuario.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbUsuario.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        javax.swing.GroupLayout pListaUsuarioLayout = new javax.swing.GroupLayout(pListaUsuario);
        pListaUsuario.setLayout(pListaUsuarioLayout);
        pListaUsuarioLayout.setHorizontalGroup(
            pListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListaUsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pListaUsuarioLayout.setVerticalGroup(
            pListaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pListaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCadUsuario.setText("Cadastrar");
        btnCadUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraUsuario(evt);
            }
        });

        btnUpUsuario.setText("Atualizar");
        btnUpUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaTelaUpUsuario(evt);
            }
        });

        btnDelUsuario.setText("Excluir");
        btnDelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluiUsuario(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnUpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pListaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pInfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pListaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pInfUsuario.getAccessibleContext().setAccessibleName("");
        pInfUsuario.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraUsuario

        if (JOptionPane.showConfirmDialog(null, "Deseja mesmo cadastrar este usuário?", "Cadastro", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icone) == JOptionPane.YES_OPTION) {

            if (txtCadNomeU.getText().equals("") || txtCadLoginU.getText().equals("") || String.valueOf(txtCadSenhaU.getPassword()).equals("") || txtCadCodU.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos para cadastrar um novo usuário!", "Atenção", JOptionPane.INFORMATION_MESSAGE, icone);
            } else {
                Usuario u = new Usuario();
                UsuarioDao daoU = new UsuarioDao();

                u.setNome(txtCadNomeU.getText());
                u.setLogin(txtCadLoginU.getText());
                u.setSenha(String.valueOf(txtCadSenhaU.getPassword()));
                u.setCodT(txtCadCodU.getText());
                daoU.create(u);

                txtCadNomeU.setText("");
                txtCadLoginU.setText("");
                txtCadSenhaU.setText("");
                txtCadCodU.setText("");

                leTabelaUsuario();
            }
        }
    }//GEN-LAST:event_cadastraUsuario

    private void chamaTelaUpUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaTelaUpUsuario

        if (TelaUpUsuario.instancia == null) {
            if (tbUsuario.getSelectedRow() != -1) {

                TelaUpUsuario upUsuario = new TelaUpUsuario();

                getParent().add(upUsuario);
                upUsuario.setVisible(true);
                upUsuario.toFront();
                upUsuario.centralizaTela();

                upUsuario.setValoresUsuario(
                        tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString(),
                        tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString(),
                        tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString(),
                        tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString(),
                        tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 4).toString()
                );
                
                this.enable(false);

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um usuário", "Atenção", JOptionPane.INFORMATION_MESSAGE, icone);
            }
        } else {
            TelaUpUsuario.instancia.toFront();
        }

    }//GEN-LAST:event_chamaTelaUpUsuario

    private void excluiUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluiUsuario

        if (tbUsuario.getSelectedRow() != -1) {
            if (JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir este usuário?", "Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icone) == JOptionPane.YES_OPTION) {

                Usuario u = new Usuario();
                UsuarioDao daoU = new UsuarioDao();

                u.setId((int) tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0));
                daoU.delete(u);

                leTabelaUsuario();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário", "Atenção", JOptionPane.INFORMATION_MESSAGE, icone);
        }
    }//GEN-LAST:event_excluiUsuario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadUsuario;
    private javax.swing.JButton btnDelUsuario;
    private javax.swing.JButton btnUpUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCadCodU;
    private javax.swing.JLabel lbCadLoginU;
    private javax.swing.JLabel lbCadNomeU;
    private javax.swing.JLabel lbCadSenhaU;
    private javax.swing.JLabel lbInfCod;
    private javax.swing.JPanel pInfUsuario;
    private javax.swing.JPanel pListaUsuario;
    public javax.swing.JTable tbUsuario;
    private javax.swing.JTextField txtCadCodU;
    private javax.swing.JTextField txtCadLoginU;
    private javax.swing.JTextField txtCadNomeU;
    private javax.swing.JPasswordField txtCadSenhaU;
    // End of variables declaration//GEN-END:variables
}
